# From Pytorch to TF2
You can easily convert models implemented in pytorch to tensorflow 2.0.
all you have to do is change module names or inherits to fit into tensorflow style

For example,

pytorch, class inherits nn.Module ->
tf2, class inherits keras.Model

pytorch, when model is called forward method is excecuted ->
tf2, when model is called call method is excecuted ->

and there is some difference in built-in layers (e.g. nn.Linear, layers.Dense)

In [33]:
import torch
import torch.nn as nn

class Torch_FF(nn.Module):
    def __init__(self, hidden_dim:int, projection_dim:int,dropout:float):
        super(Torch_FF, self).__init__()

        self.net = nn.Sequential(
            nn.Linear(hidden_dim, projection_dim), nn.ReLU(inplace=True),
            nn.Dropout(dropout),
            nn.Linear(projection_dim, hidden_dim),
            nn.Dropout(dropout),
        )

    def forward(self, x):
        out = self.net(x)
        

        return x + out

    

In [31]:
torchff = Torch_FF(10,20,0.1)
x = torch.Tensor(4,10)
torchff(x)

tensor([[ 1.6699e+16, -1.2226e+16,  2.1745e+17,  1.5110e+16,  3.5698e+14,
         -2.5156e+16, -1.7221e+16, -2.3056e+16, -8.0133e+14,  1.3911e+16],
        [-2.7368e-01,  1.1150e-01,  1.1580e-01, -6.0430e-02, -1.4547e-01,
          5.6057e-03, -2.2734e-01, -9.5633e-03,  1.2671e-01, -4.5635e-02],
        [-2.7994e-01,  1.1146e-01,  1.2826e-01, -5.7368e-02, -1.3914e-01,
         -4.9996e-03, -2.3469e-01,  1.6974e-03,  1.3594e-01, -5.1078e-02],
        [ 6.6571e-03,  9.6350e-02,  1.3770e-01, -5.7302e-02, -1.4289e-01,
          2.5392e-02, -2.5079e-01, -6.3375e-03,  1.2375e-01, -3.2977e-02]],
       grad_fn=<AddBackward0>)

In [21]:
import tensorflow as tf
import tensorflow.keras as keras
class TF_FF(keras.Model):
    def __init__(self, hidden_dim:int, projection_dim:int,dropout:float):
        super(TF_FF, self).__init__()

        self.net = keras.Sequential([
            keras.layers.Dense(projection_dim), keras.layers.ReLU(),
            
            keras.layers.Dropout(dropout),
            keras.layers.Dense(hidden_dim),
            
            keras.layers.Dropout(dropout),]
        )

    def call(self, x):
        out = self.net(x)

        return x + out

In [32]:
tfff = TF_FF(10,20,0.1)
x = tf.random.normal((4,10))
tfff(x)

<tf.Tensor: shape=(4, 10), dtype=float32, numpy=
array([[ 0.3487363 ,  0.38890618, -0.70338446,  0.8884403 ,  0.17006144,
         1.0657153 , -1.5677168 , -0.65966326, -2.0312881 ,  1.4952853 ],
       [ 1.2307484 ,  1.0156591 ,  1.3497066 , -0.17376608, -0.27518564,
        -1.2344555 , -1.1042955 ,  1.8668978 , -1.4143102 ,  1.5063248 ],
       [-1.4251554 , -0.03378266,  0.27343386,  0.30450794, -1.264427  ,
         1.0780145 , -1.395919  , -0.5393273 , -0.7790887 ,  0.35443807],
       [-1.6541156 ,  1.7075299 , -1.018358  ,  0.8926296 , -0.18365347,
        -0.3711658 , -1.6573474 ,  0.44739258, -0.67343515,  0.67227936]],
      dtype=float32)>

tensor([ 4., 10.])